# Generated by Django 5.2.1 on 2025-05-11 16:30

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_csv', models.TextField(blank=True, help_text='Разделяйте URL запятыми', validators=[gallery.models.validate_url_list])),
            ],
        ),
    ]
